# Generated by Django 4.0 on 2021-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('Description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('PreviousDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='PreviousDate')),
                ('CurrentDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='CurrentDate')),
                ('PaymentDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='PaymentDate')),
                ('FullName', models.CharField(blank=True, max_length=50, null=True, verbose_name='FullName')),
                ('BillID', models.CharField(blank=True, max_length=50, null=True, verbose_name='BillID')),
                ('PaymentID', models.CharField(blank=True, max_length=50, null=True, verbose_name='PaymentID')),
                ('Cycle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cycle')),
                ('TraceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Operator', models.CharField(blank=True, choices=[('Irancell', 'Irancell'), ('Hamrahavval', 'Hamrahavval'), ('Rightel', 'Rightel')], max_length=50, null=True, verbose_name='Operator')),
                ('TypeLine', models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('FixedLine', 'Hamrahavval')], max_length=50, null=True, verbose_name='TypeLine')),
                ('last_inquiry', models.DateField(auto_now_add=True, null=True, verbose_name='last inquiry')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['id'],
            },
        ),
    ]
