# Generated by Django 4.0 on 2021-12-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_active', models.BooleanField(verbose_name='active')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('last_inquiry', models.DateField(auto_now_add=True, null=True, verbose_name='last inquiry')),
                ('device_type', models.CharField(blank=True, choices=[('phone', 'phone'), ('car', 'car')], max_length=50, null=True, verbose_name='device_type')),
                ('Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Operator', models.CharField(blank=True, choices=[('Irancell', 'Irancell'), ('Hamrahavval', 'Hamrahavval'), ('Rightel', 'Rightel')], max_length=50, null=True, verbose_name='Operator')),
                ('TypeLine', models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('FixedLine', 'Hamrahavval')], max_length=50, null=True, verbose_name='TypeLine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code')),
                ('Description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('PreviousDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='PreviousDate')),
                ('CurrentDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='CurrentDate')),
                ('PaymentDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='PaymentDate')),
                ('FullName', models.CharField(blank=True, max_length=50, null=True, verbose_name='FullName')),
                ('BillID', models.CharField(blank=True, max_length=50, null=True, verbose_name='BillID')),
                ('PaymentID', models.CharField(blank=True, max_length=50, null=True, verbose_name='PaymentID')),
                ('Cycle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cycle')),
                ('TraceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.device')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
