# Generated by Django 4.0 on 2021-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_device_description_alter_device_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='is_active'),
        ),
    ]
