# Generated by Django 4.0 on 2021-12-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='BarCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='DateTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DateTime'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='Delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='Details',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='PlateNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PlateNumber'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='SerialNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SerialNumber'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='TotalAmount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TotalAmount'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='Type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='TypeLine',
            field=models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('FixedLine', 'FixedLine')], max_length=50, null=True, verbose_name='TypeLine'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.device'),
        ),
    ]
