# Generated by Django 4.0 on 2021-12-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_barcode_inquiry_city_inquiry_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='FinalTerm_Amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FinalTerm_Amount'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='FinalTerm_BillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FinalTerm_BillID'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='FinalTerm_PaymentID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FinalTerm_PaymentID'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='MidTerm_Amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MidTerm_Amount'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='MidTerm_BillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MidTerm_BillID'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='MidTerm_PaymentID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MidTerm_PaymentID'),
        ),
    ]
