# Generated by Django 4.0 on 2021-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_device_electricitybillid_device_participatecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('car', 'car'), ('home', 'Home')], max_length=50, null=True, verbose_name='device_type'),
        ),
    ]
