# Generated by Django 4.0 on 2021-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_device_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Operator',
        ),
        migrations.RemoveField(
            model_name='device',
            name='TypeLine',
        ),
        migrations.RemoveField(
            model_name='device',
            name='bill_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('FixedLine', 'FixedLine'), ('Irancell', 'Irancell'), ('Hamrahavval', 'Hamrahavval'), ('Rightel', 'Rightel'), ('car', 'car'), ('ElectricityBill', 'ElectricityBill'), ('GasBill', 'GasBill'), ('WaterBill', 'WaterBill')], max_length=50, null=True, verbose_name='device_type'),
        ),
    ]
