# Generated by Django 4.0 on 2021-12-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_device_operator_remove_device_typeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='BarCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BarCode'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number'),
        ),
    ]
