# Generated by Django 4.0 on 2021-12-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0012_alter_device_barcode_alter_device_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user', verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user', verbose_name='owner'),
        ),
    ]
