# Generated by Django 4.0 on 2021-12-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0015_alter_device_options_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['id'], 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterField(
            model_name='device',
            name='BarCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BarCode'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ElectricityBillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ElectricityBillID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ParticipateCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ParticipateCode'),
        ),
        migrations.AlterField(
            model_name='device',
            name='WaterBillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WaterBillID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user', verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('FixedLine', 'FixedLine'), ('Irancell', 'Irancell'), ('Hamrahavval', 'Hamrahavval'), ('Rightel', 'Rightel'), ('car', 'car'), ('ElectricityBill', 'ElectricityBill'), ('GasBill', 'GasBill'), ('WaterBill', 'WaterBill')], max_length=50, null=True, verbose_name='device_type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_inquiry',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='last inquiry'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Abonman',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Abonman'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='AverageConsumption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AverageConsumption'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='BillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BillID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='BillPdfUrl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BillPdfUrl'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='ConsumptionType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ConsumptionType'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='CurrentCounterDigit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CurrentCounterDigit'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='CurrentDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CurrentDate'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='CustomerType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomerType'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Cycle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='DateTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Details',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='FinalTerm_Amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FinalTerm_Amount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='FinalTerm_BillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FinalTerm_BillID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='FinalTerm_PaymentID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FinalTerm_PaymentID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='FullName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FullName'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Insurance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='InsuranceAmount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='InsuranceAmount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='MidTerm_Amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MidTerm_Amount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='MidTerm_BillID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MidTerm_BillID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='MidTerm_PaymentID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MidTerm_PaymentID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='PaymentDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PaymentDate'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='PaymentID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PaymentID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='PlateNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PlateNumber'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='PowerPaytollAmount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PowerPaytollAmount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='PreviousCounterDigit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PreviousCounterDigit'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='PreviousDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PreviousDate'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='SaleYear',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SaleYear'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='SerialNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SerialNumber'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='TariffType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TariffType'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Tax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='TaxAmount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TaxAmount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='TotalAmount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TotalAmount'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='TotalDays',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TotalDays'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='TraceNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TraceNumber'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
    ]
