# Generated by Django 4.0 on 2021-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_device_created_by_alter_device_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
