# Generated by Django 4.0 on 2021-12-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_inquiry_amount_alter_inquiry_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='ExtraInfo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ExtraInfo'),
        ),
    ]
