# Generated by Django 4.0 on 2021-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_device_barcode_alter_device_electricitybillid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='GasBillID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
