# Generated by Django 4.0 on 2021-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_number_device_fixedlinenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='datetime_of_inquiry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_inquiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
