# Generated by Django 4.0 on 2021-12-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_inquiry_datetime_of_inquiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='datetime_of_inquiry',
        ),
    ]
