# Generated by Django 3.2 on 2022-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0003_bank_bank_choose_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='inquiry_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(choices=[('BMI', 'BMI'), ('SEP', 'SEP'), ('ZARINPAL', 'Zarinpal'), ('IDPAY', 'IDPay'), ('ZIBAL', 'Zibal'), ('BAHAMTA', 'Bahamta'), ('MELLAT', 'Mellat')], max_length=50, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
