# Generated by Django 3.2 on 2022-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
