# Generated by Django 3.2 on 2022-01-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_inquiry_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
